### ISSUE TITLE
`DATABASE_URL` should be constructed in `base.py`, not `entrypoint.sh`

### ISSUE THREAD

**Issue by pastewka** [ContactEngineering/topobank#1037]
**Describe the issue**
Currenty, Docker `entrypoint.sh` creates and environment variable `DATABASE_URL` that contains the Postgres information, i.e. pieces together the `POSTGRES_*` environment variables. An implication of this is, however, that `docker compose exec` does not have `DATABASE_URL` in its environment and hence cannot make a proper database connection.

The solution is to directly use `POSTGRES_*` in `base.py` rather than using `DATABASE_URL`.

This will not affect deployment as we always define the `POSTGRES_*` variables.

**Comment by IoannisNezis** [comment]
I did some research and the reason is that `docker compose exec` does just not use the specified entrypoint, which makes sence. Since the environment-variable is exported in the entrypoint, `docker compose exec` does not inherit `DATABASE_URL`.

This can be verified by running
`dc exec django python manage.py createsuperuser`
vs
`dc exec django /scripts/entrypoint.sh python manage.py createsuperuser`
