### ISSUE TITLE
Takes a very long time to upload text files and for subsequent steps

### ISSUE THREAD

**Issue by abg30** [ContactEngineering/topobank#261]

**Comment by mcrot** [comment]
Hi @abg30 , I've improved the code for the topography upload with the current version 0.13.0.
Could you please test once again and give some feedback on the upload of text files from a user's perspective?
I think it is maybe to sufficiently fast yet, but should be better.

I haven't implemented the batch upload (#173) yet, this would be another improvement.

**Comment by pastewka** [comment]
I've just uploaded a text file and it's still extremely slow.

**Comment by mcrot** [comment]
Thanks for trying. Do you mean the initial upload or also the steps after?

Somehow the pure upload of the file (first page, progress bar) is very slow now (almost 3 minutes for 20MB). 
This wasn't so slow when this issues was opened. Back then it was more like that the initial file upload was reasonable fast, but the subsequent steps were very slow.

Now the upload is really slow and the subsequent steps are a bit faster, I think. Strange, because I didn't expect that the initial upload would change. I need to investigate a bit why this happens.

**Comment by pastewka** [comment]
The upload was okay for me but the following steps were slow.

**Comment by pastewka** [comment]
We should check whether this problem still persists, as we have made many changes to how topographies are loaded/cached

**Comment by pastewka** [comment]
Resolved with #1012
