### ISSUE TITLE
surfaces shared with multiple users

### ISSUE THREAD

**Issue by lthimons** [ContactEngineering/topobank#299]
when a surface is shared with multiple users, it creates a row in the sharing section for each user the surface is shared with. It might clean things up a bit if there was a dropdown list or something that the original sharer could see that listed all users the file is shared with in one row.

**Comment by mcrot** [comment]
I'm not sure whether it would be a good idea to put everything in on row, because this would not work with the current way you can remove shares or add change permissions by selecting a single row. 

Maybe an alternative is to press "Permissions" when viewing a surface. There you have a small list of only the people the surface is shared with. What do you think @lthimons ?

**Comment by lthimons** [comment]
I think a permissions button sounds very reasonable. And perhaps in the future it could be an icon that changes based on what those permissions are. if it is shared with one person vs many maybe it could change to reflect that.

**Comment by mcrot** [comment]
Well, maybe I was unclear - I meant, this "Permission" tab is already there, look [here](https://contact.engineering/manager/surface/132/#permissions) or at this screenshot:
![grafik](https://user-images.githubusercontent.com/9113541/100253407-5d528180-2f41-11eb-9dd6-e099c93e624f.png)

Do you think this is an alternative to your suggestion, to just go there or do we need to change the sharing tab?

**Comment by lthimons** [comment]
I didn't see the permissions button earlier in the surface view. I like that a lot. I think it works in its current state as shown in that screenshot. Is there any way to do something similar on the sharing menu that, as of now, lists everyone that a surface is shared with on a separate row? This seems to create multiple entries per surface based on who it is shared with.

**Comment by mcrot** [comment]
Hm - there is indeed a row for each person the surface was shared with. This is intended because of the control checkboxes and buttons:
![grafik](https://user-images.githubusercontent.com/9113541/101169116-c5d5e880-363c-11eb-902b-333cfda0cfba.png)

So you can choose which user should receive change permissions or which from which users you want to withdraw permissions.
If everything is in one row, I cannot do it this way.

In the next version (0.9.6), the shares will be sorted by default this way:

1. Surface name
2. Shared with

So you see all persons a surface is shared with next to each other. Is that helpful?

Or could you explain in more detail what you want to achieve? I haven't understood yet.

**Comment by mcrot** [comment]
Hi @lthimons , is this still relevant?

**Comment by pastewka** [comment]
This part of the user interface has been completely revised. You can now search for sharing info in the main search overview.
