### ISSUE TITLE
Fill missing data points

### ISSUE THREAD

**Issue by pastewka** [ContactEngineering/TopoBank#321]
We need capabilities to fill in missing data points

**Comment by tdbjacobs** [comment]
@pastewka, @mcrot, 

It appears that this functionality (filling in missing data) *has* been added to the web app. 

My student Meg reports (screenshot below) that when she uploads samples with missing data, the web app result shows no missing data. (In her case, there was a lot of it!)

On the one hand, I'm happy we have implemented this. Good job! And much needed functionality! 

On the other hand, I'm not happy that it's not notifying the user that it is filling in interpolated data. I'd suggest adding a warning to the user, and also specifying the percent of pixels that have been filled in. We can also consider possibly coloring/shading the pixels differently to designate that they have been filled in. 

-Tevis

<img width="845" alt="Screen Shot 2021-07-23 at 1 06 19 PM" src="https://user-images.githubusercontent.com/22891610/126818076-6258bf69-dd54-44ee-a0cd-a991d2f6f40c.png">

**Comment by pastewka** [comment]
This has *not* been added to the webapp. I am not sure what is going on. @mcrot can you check what is happening here?

**Comment by tdbjacobs** [comment]
Hey Meg,

I wanted to loop you into this discussion - but I don't know your github
handle, so I'm adding you on to the email thread.

Can you please reply-all to this email and attach the raw file (opd format,
or whatever) that was used to create the below screenshot?

Thanks,

Tevis
[image: Screen Shot 2021-07-23 at 1.06.19 PM.png]



Tevis Jacobs
William Kepler Whiteford Faculty Fellow and Associate Professor
Mechanical Engineering and Materials Science
University of Pittsburgh
http://www.engineering.pitt.edu/JacobsLab/
Mail: 636 Benedum Hall, 3700 O'Hara St., Pittsburgh, PA 15261
Office: 538-E Benedum Hall, 412-624-9736
***@***.***

**Comment by mcrot** [comment]
Hi all, Meg's GitHub handle is @megannescio, so now she's also included here in this discussion, I think.

Yes, it would be useful to have the file, either sent by mail or alternatively, you could also share that surface with me inside the web app (read-only). Then I can also look up was happend to that topography in the logs.

@pastewka ist right, we haven't implemented the filling of missing data points explicitly. I'm also not sure what 
has happened here, yet. What maybe is the case that the internal conversion of data to NetCDF, which now always happens for speed up reasons, has filled the points. Or it's the plotting routine. I have to check that with a file having missing points.

**Comment by pastewka** [comment]
I think you are right, it is the NetCDF business. You can specify [fill values](https://www.unidata.ucar.edu/software/netcdf/docs/fill_values.html) to fill in missing that and that may be handled in a wrong manner. The scipy netcdf implementation may actually treat this different from the Unidata one.

**Comment by mcrot** [comment]
Hm .. I've tested it and I think the NetCDF is doing okay with my little example with missing data points. Please
see #699. I've opened a new issue for this, because it seems to be a bug which is different from the original feature request 
in the issue here.

In that example, the NetCDF looks exactly the same as what the readers git from the original file.
And I assume that the analysis functions in `SurfaceTopography` know how to handle masked arrays. 

So the question is, what the plotting does with masked arrays. I think missing values are either not displayed as black spots 
so far or the fill value of masked arrays is taken somehow, not sure what's going on there. I'll continue that in #699, so this
issue can be kept open when the problem is fixed.

**Comment by mcrot** [comment]
Just to summarize #699 so all are notified:
- filling missing points has not been implemented yet
- the filling in the example above is caused by a [bug in the `SurfaceTopography` library](https://github.com/ContactEngineering/SurfaceTopography/issues/126)
- it has quite some impact: For measurements with missing points, the squeezed files and all analyses need to be recalculated; if there were downloads of the related surfaces, the respective squeezed files in there would be wrong

**Comment by pastewka** [comment]
I've implemented the filling of missing data points on the backend, see here: https://github.com/ContactEngineering/SurfaceTopography/pull/169 - the pipeline function is called `interpolated_undefined_data`.

It should be easy to add an option to enable filling of missing data points.

**Comment by mcrot** [comment]
Is this correct, @pastewka ?

- this option should be global for each measurement
- if chosen, this pipeline function is applied before every usage of the data like detrending

**Comment by pastewka** [comment]
Exactly. I still need to work on the backend but will hopefully be finished this evening. (I have a better idea how to do the imputation.)

**Comment by pastewka** [comment]
I do believe that this feature is highly requested since more and more optical measurements are uploaded to the web app,

**Comment by pastewka** [comment]
The PR ready now. I've asked @AntoineSIMTEK to look at it.

**Comment by pastewka** [comment]
`SurfaceTopography` 0.100.0 has the data imputation - I'll now work on putting it into `TopoBank`

**Comment by mcrot** [comment]
I'm working on it and hope getting it online today.

**Comment by tdbjacobs** [comment]
No rush.  We just wish to test it once it goes live! :)

-Tevis



Tevis Jacobs
William Kepler Whiteford Faculty Fellow and Associate Professor
Mechanical Engineering and Materials Science
University of Pittsburgh
http://www.engineering.pitt.edu/JacobsLab/
Mail: 636 Benedum Hall, 3700 O'Hara St., Pittsburgh, PA 15261
Office: 538-E Benedum Hall, 412-624-9736
***@***.***
