### ISSUE TITLE
Labels of colorbars should be next to colorbars, not on top

### ISSUE THREAD

**Issue by AntoineSIMTEK** [ContactEngineering/TopoBank#592]
![grafik](https://user-images.githubusercontent.com/40853209/111287639-b60a6f00-8643-11eb-99ba-272af261569a.png)

That is my opinion. What do you think @pastewka

**Comment by pastewka** [comment]
Ageed, the labels should be next to the colorbar.

I never realized this, but the units are bogus. The units here should be um. We also should *under all circumstance* avoid the e Notation. Please change this to 10^-4. This has a high priority!

**Comment by AntoineSIMTEK** [comment]
I think it depends wether I give the sizes as 0.0005 m or 0.5 mm


![grafik](https://user-images.githubusercontent.com/40853209/111289641-a3913500-8645-11eb-9df6-683d15449cfb.png)

**Comment by AntoineSIMTEK** [comment]
I find this actually fair. That way the users is able to choose his prefered unit

**Comment by mcrot** [comment]
I'm currently implementing this. Can we write "Contact pressure p(E*)" shorter without loosing clarity?
For example: "Pressure p(E*)" with "Contact"?

Otherwise I cannot currently only make it fit by shifting the tick labels of the colorbar much more to the right:
![grafik](https://user-images.githubusercontent.com/9113541/115053134-1577cb00-9edf-11eb-94c3-13f02b0e5bb8.png)

I think the color title should also be shorter in order to make the plot more compact.

**Comment by mcrot** [comment]
Okay, I'm using "Pressure p(E*)".

**Comment by AntoineSIMTEK** [comment]
What we usually do is to rotate the title of the colorbar, like the y label.

**Comment by mcrot** [comment]
Okay, thanks. I'm not sure whether bokeh allows this, let me see.

Something else: What are the units of "pressure" here? Isn't it also normalized? 
The current version shows no unit at all for the pressure plot.

Shouldn't we say "Normalized pressure p/E*" here, like on the x axis on the left side?  Or is the unit missing?

**Comment by pastewka** [comment]
The unit is "E*"

**Comment by mcrot** [comment]
> What we usually do is to rotate the title of the colorbar, like the y label.

Although there are several properties to change the title of a colorbar, there is no easy way to write it vertically.
It is maybe possible by adding a third "column" to the plot which only contains the text, but I guess that
would cause some problems for calculating the correct width of the plot. I would like to leave it above the colorbar at the moment, unless it had a high priority to display it vertically.

**Comment by mcrot** [comment]
There are some issues open in bokeh related to this issue here:
https://github.com/bokeh/bokeh/issues/10326
https://github.com/bokeh/bokeh/issues/7093

They're having been open since quite a while, there is a Github project to work on these issues:
https://github.com/bokeh/bokeh/projects/11#card-51564854

**Comment by mcrot** [comment]
I've had to limited the distance between colorbar and its tick labels in order to have the ticks always shown
with our formatter. Therefore there is not so much space for the colorbar title and I've truncated "Displacement" to "Displacem.":
![grafik](https://user-images.githubusercontent.com/9113541/116386851-7924c100-a81a-11eb-832a-8c40d7240892.png)

If bokeh makes progress here, we can again improve it. According the comment [here](https://stackoverflow.com/a/46855747/10608001) they would appreciate some help for the colorbar issues due to limited resources.
