### ISSUE TITLE
Show publication date next to the version number in overview

### ISSUE THREAD

**Issue by pastewka** [ContactEngineering/TopoBank#608]
Right now, there is no way to see when a data set was published, but I think this is crucial information:
![grafik](https://user-images.githubusercontent.com/2530391/111793377-8074b880-88c5-11eb-97fe-f04ca82009ba.png)

We should display the publication data next to the version information or in a separate column. This is related to #479.

**Comment by mcrot** [comment]
Yes, we can display it as an extra column. However, it is already displayed when you view a published surface:
![grafik](https://user-images.githubusercontent.com/9113541/113160371-bc9d0700-923d-11eb-98bd-f02f3b455a87.png)

**Comment by pastewka** [comment]
Okay, nice!

**Comment by mcrot** [comment]
Should this still be added to the Search results as an own column, since the publication date is available on the detail page
in the version button?

If yes, this would need horizontal space in all rows, which cannot be used for long names/tags.
The column header for the publication date should be as short as possible, e.g. "Pub Date" or just "Date".

As alternative - what about a tooltip at the version number?

**Comment by pastewka** [comment]
We need an additional column. The date is more important than the version number, I'd vote to remove the version number and replace it with the date. A search should then only find the highest version of a dataset. Any thoughts @tdbjacobs

**Comment by pastewka** [comment]
Let me make this more specific. We should the date of version 1 and underneath the date of the highest version (if not =1), maybe with a text "last updated on". The "WIP" version is only shown in the search results if there is no published version.

**Comment by mcrot** [comment]
I'm okay with removing the version number and showing a date - although it has one disadvantage: You cannot see by "last update" date alone that a surface is a published surface, only by the little tag label "published", which is still visible.

About the suggestion with the two dates in one date field: I'm not sure that for a user it is clear what that actually means.
Why showing the date of version 1 and not only showing the "last updated on" date and use this also as column header? 

So far, every surface instance in the database (so e.g. "WIP" and "Version 1") is an own row in the search result.
Each of them could be shown with a "last update" date. 

About hiding the "WIP" version: I think it should not be hidden on the select page, because as a creator or collaborator, I want to see it and be able to edit it. And if a surface is not shared with a user, already now only the published versions are visible,
because the user has no permission to see it.

Maybe I completely misunderstand your proposal?

Probably you mean this: Every related "thread" of surfaces ("WIP"->"Version 1"->"Version 2"->...) should only get one row in the search result? This could be done with an extra widget, some kind of "Version dropdown" like on the detail page
which only shows the versions which apply to the search and filter terms.

**Comment by tdbjacobs** [comment]
I suspect that most of our surfaces will be published once and never
changed. (i.e. they will only have one version)

Therefore, we could probably hide the version number for v1 and only show
the date. But if a surface HAS been updated, then a button appears like
"See older versions". When viewing an older version, it can give info like
"V2, updated 3 May 2020"

(PS - What format are we using for dates? We want it to be US and EU
compatible - so CANNOT use "5/3/20")

-Tevis


Tevis Jacobs
William Kepler Whiteford Faculty Fellow and Associate Professor
Mechanical Engineering and Materials Science
University of Pittsburgh
http://www.engineering.pitt.edu/JacobsLab/
Mail: 636 Benedum Hall, 3700 O'Hara St., Pittsburgh, PA 15261
Office: 538-E Benedum Hall, 412-624-9736
***@***.***

**Comment by pastewka** [comment]
I think the best date format is spelling out the month, i.e. "Apr. 3, 2021".

Even if only a single published surface is shown, you can still navigate to WIP by clicking on it and then choosing WIP. I think it is very confusing to a novel user if multiple results of the same surface show up. There should only be a single search result for let's say our UNCD surface.

**Comment by mcrot** [comment]
Hm - I guess we need to rethink what the Search page does. If the user searches for a certain word
and it's used in the description of the WIP surface, but not in the published version, at least then the WIP version should show up.
Similar if some filter values changes, e.g. the category (although this is unlikely, but it can happen).

What about this idea: Instead of a date, there is a dropdown with publication dates or "Work in Progress", like 
on the detail page. It would only list the versions which apply to the search and filter terms.

I still think the default version shown should be the WIP version and not the published version, because this is what the user is working with. Wouldn't it be more confusing to show the published version only? Maybe it's better to discuss this in person,
I still don't understand why showing the published version only is an improvement.

**Comment by mcrot** [comment]
Okay, I've talked to Lars. Result:

We keep a column "version" but also show the publication date there, e.g. "1 (Apr. 3, 2021)". There will be
still multiple results according to search term and filters.

Concerning the date format: On the dropdown button on the detail page, I have "Version 1 (2021-04-03)" instead, so
the ISO format, which I personally find more practical in a list than a format with written month names. 
However, I could also use "Version 1 (Apr. 3, 2021)" there to make it consistent, if you like.

**Comment by pastewka** [comment]
ISO-format is fine @tdbjacobs any opinion?

**Comment by tdbjacobs** [comment]
fine with iso format. i think it's used commonly enough to be recognized.
-tevis

Tevis Jacobs
William Kepler Whiteford Faculty Fellow and Associate Professor
Mechanical Engineering and Materials Science
University of Pittsburgh
http://www.engineering.pitt.edu/JacobsLab/
Mail: 636 Benedum Hall, 3700 O'Hara St., Pittsburgh, PA 15261
Office: 538-E Benedum Hall, 412-624-9736
***@***.***
