### ISSUE TITLE
Long names and many measurements in a surface

### ISSUE THREAD

**Issue by RLeute** [ContactEngineering/TopoBank#692]
Dear Michael,

I have really long names for measurements containing all the specifications of the simulation on the "analyze-page" the names are cut and I can not properly select the single measurements.

Additionally, it might be useful to scroll through the measurements. Thus one can see what changes in the plot if one selects or deselects a single measurement. If the list is too long and one clicks on a measurement at the end one can not see the plot anymore because the whole screen is filled with the list.

Also for many measurements, it might be useful if the selected measurements in one plot can be automatically selected in all other plots. Otherwise I have to select in e.g. PSD and VBM and other plots always the same measurements by hand.

I have shared the surface [956](https://contact.engineering/manager/surface/956/) with you such that you can see my problems

**Comment by mcrot** [comment]
Dear Richard,

Thanks for your message and for sharing the surface. There are three things you are mention here:

## Analyze page

I'm not fully sure what list of names you are referring to on the "Analyze" page. There are several places possible. 
You mean the selection dialogue under each plot, right? 
If it is about the first column in the Roughness Parameter table, see #560. This will be fixed in the next version.

## Scroll through the measurements

I understand .. if we would have some fixed area in which scrolling is possible, the plot could stay at a fixed place
without scrolling away.

## One selection for multiple plots

Would it be better to have one selection dialogue for all plots?

I'm not sure how to implement this, because currently the plots are individual and also individually loaded
and it's probably not straightforward to address several plots at once from Javascript..

I need to discuss this with the others.

**Comment by RLeute** [comment]
Dear Michael,

sorry for being imprecise in describing my problems. A picture like in #560 describes a problem much easier and better, I should stick to such a descriptions.

## Analyze page
Yes, I meant the selection dialogue under each plot 
![topobank_issue-692-pic1](https://user-images.githubusercontent.com/34573535/123935947-fdb7cb00-d994-11eb-9eb5-0e793b28fb7f.png)

## Scroll through the measurements
Yes, I was thinking of something like this

## One selection for multiple plots
For me a single selection dialogue would be fine, but I am not sure if this is true for all users....

**Comment by mcrot** [comment]
Dear Richard,

Thanks for the screenshot! I've discussed this yesterday with Lars.
Actually, there is already sth which is similar to what you suggested.
The page "Find & select" allows to scroll (and search) for individual measurements. You see the full name
with a description:
![grafik](https://user-images.githubusercontent.com/9113541/124081093-66617f00-da4b-11eb-9a28-3a6a0f93211a.png)

Here you can select individual measurements and press the *green* Analyze button in the top area, where all selected items are listed:
![Screenshot 2021-07-01 at 09-06-03 contact engineering - Store and analyze surface topography measurements](https://user-images.githubusercontent.com/9113541/124081834-4d0d0280-da4c-11eb-9358-c289d520876a.png)
 
This will narrow all plots to the selection. Did you try that? 

You can also *open a new tab with a right click on "Analyze"* and have different tabs with different selections.
Like this you have both, scrolling and one selection for all plots. And your analysis downloads are also narrowed to the selected measurements.

Doing this all on the "Analyze" page is a bit difficult with the current implementation and probably not all users want one common selection for all plots.

Does this help?

**Comment by mcrot** [comment]
What you can also do here is to assign tags to individual groups of measurements and select the tags to compare the corresponding analyses.

**Comment by RLeute** [comment]
Hi Michael,
thanks for the explenation, this perfectly solves my problems!
