### ISSUE TITLE
DOIs for published data sets

### ISSUE THREAD

**Issue by pastewka** [ContactEngineering/TopoBank#731]
We currently have permalinks of the form https://contact.engineering/go/abcdef. It would be useful to also have DOI for each dataset, since this seems to be the accepted citation format and some funding agencies (e.g. the ERC) only allow DOIs for listing published data set.

**Comment by mcrot** [comment]
So far, the calculated from the ID of the publication object. And this ID is only available after publishing.
Two ideas about this:
1. We could use other means to calculate the URL instead of the id, e.g. a hash of title and authors - but this can change if you change the content and I'm not sure that the go link will still that short. This may get complicated with #762 and #780 .
2. We could introduce states to publication objects, e.g. "in preparation" and "finalized". The user than could create a publication in a "preparation" state, get the ID and the go link. There would be a list of publications in preparation. Later he/she would press "Finalize" and the publication cannot be changed any more.   

I like the second alternative more, since it seems to be more robust and comfortable. 
However it needs some more UI elements:
- on publication form an extra button for state "in preparation"
- list of own publications with states (in preparation, finalized) and future DOIs
- optional: edit publications if not yet finalized, e.g. adding an author, changing the license 
- deletion of publications which have never finalized

What do you think @pastewka ?

**Comment by pastewka** [comment]
I don't fully understand this, the id exists once published, correct? I think this is sufficient.

**Comment by mcrot** [comment]
Yes, once published then the id exists and therefore also a DOI. At end of October we talked about DOIs and I've understood that users may need to have a DOI already before publishing in order to use it when preparing papers. If this is not needed, we also don't need my those suggestions with "in preparation" etc.

**Comment by pastewka** [comment]
Let's not worry about this. You get the DOI once published.
