### ISSUE TITLE
Warning/error for average PSDs

### ISSUE THREAD

**Issue by ArushiPradhan** [ContactEngineering/TopoBank#774]
I am getting this warning/error on calculating the average PSD for this surface. The files in the surface are .OPDx files. The calculations for a similar surface is working so I am not sure why I am getting this warning.
![image](https://user-images.githubusercontent.com/78487900/145586854-e14068e0-3aec-41a6-95e5-57285cad6257.png)
![image](https://user-images.githubusercontent.com/78487900/145586898-deb9a52d-3be1-4cf3-97d9-934b6abbbc8c.png)

**Comment by mcrot** [comment]
I'm not fully sure, but I think this is related to #755 . The PR #758 has a fix, this will be installed with the next release
which should be released soon.

Here a restart of the analysis seems to fix it. Please check again the surface and let me know if there are more like this.

**Comment by mcrot** [comment]
It looks like that this has been solved in the meanwhile. The average analysis mentioned here should be available
as far as I can see.

This issue was related to problems with the underlying memcached  client.
Currently memcached is no longer used. I'm closing this, please reopen if this happens again.
