### ISSUE TITLE
http does not redict to https

### ISSUE THREAD

**Issue by pastewka** [ContactEngineering/TopoBank#835]
When typing contact.engineering without the https prefix on a fresh browser (that has never been to the site) it does not load. I don't if this is a problem with the configuration of the site itself or the DNS entry.

![BE17A83F-A550-4C1D-A6F3-29BEC000D447](https://user-images.githubusercontent.com/2530391/169453233-f60e2e7d-4df6-44d9-bc25-9f0c70bc3ef6.png)

**Comment by mcrot** [comment]
I've tried it on a private window in Firefox and the redirection worked.
Then I opened Chrome, deleted all cookies and opened an incognito window, then I could reproduce this.
The Caddy proxy [should redirect automatically](https://caddyserver.com/docs/automatic-https), but the problem was
that port 80 was closed. I've changed that, for me it works now, please try again.
