### ISSUE TITLE
Contact Mechanics crashes for the rough sphere of the contact.engineering paper

### ISSUE THREAD

**Issue by sannant** [ContactEngineering/TopoBank#867]
![image](https://user-images.githubusercontent.com/40853209/181497582-1f302c5c-b6c8-475d-bc9a-bceaf39bc689.png)

**Comment by pastewka** [comment]
Same here for a different topography
![image](https://user-images.githubusercontent.com/2530391/181512809-b0892a45-5f6e-42e3-9077-30437a577146.png)

@mcrot - can you check what is going on?

**Comment by mcrot** [comment]
Yes, I'll have a look today.

**Comment by mcrot** [comment]
I think the problem is the following: The new version of SurfaceTopography has version number 1.0 and does
not report the `micro` field. This was done for the versions before:
![grafik](https://user-images.githubusercontent.com/9113541/182131098-42cfca15-6cf7-4cb5-a2cc-78d54b965d39.png)
In my code I haven't checked that the `micro` field could be `None`. On each start a new database entry for this dependency is generated - this should not be allowed, I did not expect that. On retrieval of the on entry the result is then not unique as expected (several "None"s for micro field) and this generates an exception.

**Comment by mcrot** [comment]
It would be good to to next release of SurfaceTopography with version number 1.0.1 (micro filled).
Additionally I will look for a quick fix which sets the field to zero, when missing.

**Comment by mcrot** [comment]
Actually I've just deleted the double entries and it seems to work now. The "None" value should be handled in a similar way than 0. I'm not sure why the double values existed.

**Comment by mcrot** [comment]
@sannant Now it seems to work. Could be check please?

Not sure yet how these double entries were created - the code should not allow this.
Maybe two stacks in parallel? One  started with "docker-compose" instead of "docker-stack"?

**Comment by sannant** [comment]
It is fixed thanks
