### ISSUE TITLE
Search by person?

### ISSUE THREAD

**Issue by tdbjacobs** [ContactEngineering/TopoBank#896]
When I'm looking for a set of surfaces sent by a particular person, I often try searching by their name. But this does not seem to bring up their surfaces. (For instance, even though Ky has sent me several surfaces, when I search "Ky" -- nothing shows up.)

Would it be possible to include the creator (and maybe other people associated with a surface) in the search terms?

Thanks,

Tevis

**Comment by mcrot** [comment]
Sure! Indeed the creator is currently not included in the list of examined fields.

**Comment by mcrot** [comment]
I'm currently implementing that. 

So far the creator of a measurement or surface is not shown in the search result (only publishers).
So I wonder whether this could confuse some users, because the term because of which a measurement was found is not visible. Should we add the surface or measurement creator to the display of search results?
What do you think @tdbjacobs , @pastewka ?

**Comment by pastewka** [comment]
Yes, please add this information to the search results. I think this is only necessary for unpublished datasets.
