### ISSUE TITLE
Remove dependencies

### ISSUE THREAD

**Issue by pastewka** [ContactEngineering/topobank#915]
The whole Python stack has around 680 MB at present. The largest contributors are:

* scipy, around 100 MB
* bokeh, around 75 MB
* botocore, 70 MB
* fontawesomefree, 62 MB
* pandas, 58 MB
* django, 44 MB
* numpy, 32 MB
* gevent, 24 MB
* matplotlib, 23 MB
* lxml, 19 MB

Can we get rid of any of those? I think we should work towards removing pandas at least. That package adds no useful functionality, it's just a convenience wrapper.

**Comment by pastewka** [comment]
We may also be able to life without scipy.

**Comment by mcrot** [comment]
Well, it should be possible to either remove the `fontwaesomefree` dependency or reduce the files needed to a minimum (https://fontawesome.com/v6/docs/web/setup/host-yourself/webfonts).

I'm wondering, why `botocore` takes so much space  - it's just an interface for AWS?!

Concerning pandas, it's only used for exporting Excel files at two places in the code. Could be replaced by  `openpyxl`. Since #908 and #909 are related, this could be taken into account there.

**Comment by pastewka** [comment]
I think `botocore` is not just S3 but the whole AWS stack. We probably can't be get rid of that one.

**Comment by pastewka** [comment]
I also don't understand why Bokeh is 75 MB.

**Comment by pastewka** [comment]
The `scipy` dependency comes solely from `NuMPI`, where it is actually not needed.

**Comment by pastewka** [comment]
The things we can remove are:
- [ ] scipy
- [ ] fontawesomefree
- [ ] pandas

**Comment by pastewka** [comment]
We can't get rid of `scipy` in `SurfaceTopography` as a sparse solver is required for the filling of undefined data points

**Comment by mcrot** [comment]
I'm just configuring a new development machine, `SurfaceTopography` version  1.2 is used and I had to add `scipy` manually as dependency, because the Matlab reader imports `scipy`, but in the requirements file and `setup.py` of `SurfaceTopography`, it is not listed. So also needed for the Matlab reader. Shouldn't we list `scipy`explicitly in the requirements / `setup.py` of SurfaceTopography?

**Comment by pastewka** [comment]
I've already done this, see here: https://github.com/ContactEngineering/SurfaceTopography/pull/246 - but this should be 1.3 because it may break other things.

I'm currently preparing 1.2.1 that has a critical fix in the X3P reader. Please use that one. Will add the scipy dependency there as well.

**Comment by pastewka** [comment]
I have changed my mind here - I don't think we should pursue this. Closing this issue.
