### ISSUE TITLE
Add system status route

### ISSUE THREAD

**Issue by pastewka** [ContactEngineering/topobank#919]
I suggest to use `django-watchman`: https://github.com/mwarkentin/django-watchman

**Comment by mcrot** [comment]
Good idea, interesting package!

How we should use the watchman, shall we use Pingdom and call the URL regularly? 
Or just having a look at the Dashboard hat first?
Shall we add an env variable to configure an authentication token or should the dashboard be open for everyone?

Maybe it would be also interesting to try out this, in order to understand exceptions in production quickly:
https://docs.sentry.io/platforms/python/guides/django/
